### ISSUE TITLE
any configure to avoid click around confirm to close confirm?

### ISSUE THREAD

**Issue by woshixiaoqianbi** [Jaspero/ng-confirmations#1]

**Comment by flauc** [comment]
Hi @woshixiaoqianbi 

```
export interface ConfirmSettings {
    overlay?: boolean; // Default: true
    overlayClickToClose?: boolean; // Default: true
    showCloseButton?: boolean; // Default: true
    confirmText?: string; // Default: 'Yes'
    declineText?: string; // Default: 'No'
}
```

I think ` overlayClickToClose?: boolean;` is what you're looking for.

**Comment by woshixiaoqianbi** [comment]
@flauc i have tried... this prop cant work...
by the way, https://jaspero.co/resources/projects/ng-confirmations 
this demo overlayClickToClose cant work...

**Comment by flauc** [comment]
You are right. Thank you for pointing it out. 👍 
I will look in to it today.

**Comment by woshixiaoqianbi** [comment]
@flauc looking forward to fixbug :)

**Comment by flauc** [comment]
Sorry for the huge delay, should be fixed now though.
