### ISSUE TITLE
I start facing this issue after updating to Angular 5 latest version

### ISSUE THREAD

**Issue by umfaruki** [Jaspero/ng-confirmations#10]
I start facing this issue after updating to Angular version 
my package.json file:
 "@angular/animations": "^5.0.0",
    "@angular/cdk": "^5.0.0-rc.1",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",

 Error
Module '"/node_modules/@jaspero/ng2-confirmations/ng2-confirmations"' has no exported member 'JasperoConfirmationsModule'.

Module '"/node_modules/@jaspero/ng2-confirmations/ng2-confirmations"' has no exported member 'JasperoConfirmationsModule'.

**Comment by flauc** [comment]
Hi @umfaruki we had to go through renaming the library. Can you try installing: 
```
npm install --save @jaspero/ng-confirmations
```
Instead of ng2-confirmations?

**Comment by umfaruki** [comment]
still same error

this is my package.json if it may help

  "private": true,
  "dependencies": {
    "@ angular-devkit/core": "0.0.28",
    "@ angular/animations": "^5.0.0",
    "@ angular/cdk": "^5.0.0-rc.1",
    "@ angular/common": "^5.0.0",
    "@ angular/compiler": "^5.0.0",
    "@ angular/core": "^5.0.0",
    "@ angular/flex-layout": "^2.0.0-beta.12",
    "@ angular/forms": "^5.0.0",
    "@ angular/http": "^5.0.0",
    "@ angular/material": "^5.0.0-rc.1",
    "@ angular/platform-browser": "^5.0.0",
    "@ angular/platform-browser-dynamic": "^5.0.0",
    "@ angular/router": "^5.0.0",
    "@ ngx-loading-bar/core": "^1.1.0",
    "@ ngx-loading-bar/http-client": "^1.1.0",
    "angular2-cookie": "^1.2.6",
    "bootstrap": "^4.0.0",
    "bootstrap-sass": "^3.3.7",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "moment": "^2.20.1",
    "ng2-ckeditor": "^1.1.9",
    "ng2-toasty": "^4.0.3",
    "oidc-client": "^1.4.1",
    "primeng": "^5.2.0-rc.1",
    "rxjs": "^5.5.2",
    "webpack": "^3.8.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@ angular/cli": "1.6.5",
    "@ angular/compiler-cli": "^5.0.0",
    "@ angular/language-service": "^5.0.0",
    "@ types/jasmine": "~2.8.5",
    "@ types/jasminewd2": "~2.0.2",
    "@ types/node": "~9.3.0",
    "codelyzer": "~4.1.0",
    "jasmine-core": "~2.9.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.2.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.6.2"
  }

**Comment by flauc** [comment]
Hmm, I don't see `@jaspero/ng-confirmations` in your dependencies at all.
