### ISSUE TITLE
Dialog appears twice in latest FireFox version

### ISSUE THREAD

**Issue by keithlee7088** [Jaspero/ng-confirmations#11]
Greetings,

While testing out this plugin across several browsers (Chrome, IE 11, Firefox), I realized that only in Firefox the dialog box will appear twice when prompted. 

I assumed it was an error from my code side but the same thing also happen with the official demo page. 

**Firefox version:** 58.0.2 (64-bit)

Thanks.

**Comment by flauc** [comment]
The latest version should be working as expected now. Please let me know if you're still experiencing this with `0.4.5`
