### ISSUE TITLE
focus is not set by default on confirm box or it's button

### ISSUE THREAD

**Issue by vscodeguru** [Jaspero/ng-confirmations#12]
Hi,
   is it possible to set to focus by default to any YES or No button or confirm box.
  **Issue**
   let consider my focus is on a save button and i press enter key it need to initiate your confirm box.
   and user press enter key more than once it open your confirm box again and again..

**Comment by flauc** [comment]
Hi @vscodeguru 
This is a great point, thank you for submitting this. 
We will have this implemented asap.
