### ISSUE TITLE
Popup not showing in angular5 

### ISSUE THREAD

**Issue by rahulkr7010** [Jaspero/ng-confirmations#17]
My app has multiple modules. In the main module I imported the module as 
`JasperoConfirmationsModule.forRoot() `

and added 
`<jaspero-confirmations></jaspero-confirmations>` in the app.component.html.

I created the popup in a component from another module as 
 ```
this._confirmation.create('Confirm!', 'Are you sure you want to delete this?')
        .subscribe(res => {

          console.log(res);

        }, err => {

          console.log(err);

        });

```
.But nothing happened. I added breakpoint. Then hoovering mouse over the 'res' it shows 

> 'Unexpected end of Input'

. No error in the console.

**Comment by flauc** [comment]
Hi @rahulkr7010, 

Can you try to create a plunker with the error reproduced, please?

**Comment by rahulkr7010** [comment]
Its a large project.Unable to create project in Plunker .Sorry.  I imported module in the app.module.ts and `<jaspero-confirmations></jaspero-confirmations> `given in the app.component.html. I import the service and create function called in another component in another module. So do you think multiple module is the reason for this issue?

**Comment by flauc** [comment]
No, that shouldn't be the case. We use this library in a number of our projects structured like that. Are you importing the module in any other of your project modules? Are you adding the service in any of the providers?

**Comment by rahulkr7010** [comment]
No.Sorry for the late reply. Here we have some power failures

**Comment by rahulkr7010** [comment]
I have created a stackblitz pls check https://stackblitz.com/edit/angular-4pa4x4?file=app/another-module/another.module.ts

**Comment by flauc** [comment]
Hmm, is that stackblitz working for you, it isn't running for me?

**Comment by rahulkr7010** [comment]
Its working Now. But I dosen't work in my project. Now I am closing this issue. Probably its my fault. Let me check again. Thanks for your support

**Comment by flauc** [comment]
My pleasure, sorry you're experiencing this.
