### ISSUE TITLE
Could you please make buttons classNames customizable ?

### ISSUE THREAD

**Issue by simokhalil** [Jaspero/ng-confirmations#3]
It would be a very good thing to be able to change class names for action buttons(primary/default) through settings object (i.e. confirmClass/declineClass), rather than having to create CSS rules spacifically for them.

I you can't, I will dig into it when I'll have some time and make a PR.

Thanks by advance.

**Comment by aasukisuki** [comment]
I submitted this PR which should allow for easy customization of the existing classes:  https://github.com/Jaspero/ng2-confirmations/pull/4

I do this locally by using bootstrap 4 mixins to easily style the button.
