### ISSUE TITLE
Problem on firefox 56.0

### ISSUE THREAD

**Issue by dandro32** [Jaspero/ng-confirmations#6]
Hello,
It seems that confirmation box is displaying two times on firefox (got 56.0 - 64 bits). First time quickly display and shutdown, second is ok. On chrome or Edge everythings ok.
My friend also tested on same version, on 32 bits, the same problem.

Thanks by advance.

**Comment by flauc** [comment]
Hi @dandro32,

I'm really sorry for the long wait, I'm actively trying to figure out why this is happening, will hopefully have something soon.

**Comment by flauc** [comment]
It looks like it was the @angular/animations part of the library was causing the problems, but I couldn't figure out what exactly, so we moved back to classic css animations. Tested in firefox and looking good.

**Comment by dandro32** [comment]
Thanks :)
