### ISSUE TITLE
Close button not showing

### ISSUE THREAD

**Issue by goncalvez** [Jaspero/ng-confirmations#7]
I'm setting the option showCloseButton = true, but the button "X" is not showing....

**Comment by flauc** [comment]
should be working as expected now, sorry for the long wait.

**Comment by davidbet2** [comment]
Hi, how can i put the 'X' button at top of the modal?

**Comment by flauc** [comment]
Unfortunately, that isn't available as a feature at the moment. The fastest way currently, would be to fork the repo and extend the confirmation.component

**Comment by davidbet2** [comment]
i have the code, but the problem when you udate the repo the change be loss, in the node_modules in the file ng-confirmations.umd.js at the template i use the next code

template: "<div *ngIf=\"incomingData.overlay\" class=\"jaspero__confirmation_overlay\" [class.active]=\"animationState === 'enter'\" (click)=\"overlayClick()\"></div> <div class=\"jaspero__confirmation_dialog\" [class.active]=\"animationState === 'enter'\" > <div class=\"jaspero__confirmation_dialog-title\"> <jaspero-variable-content [isTemplate]=\"incomingData.titleIsTemplate\" [item]=\"incomingData.title\"></jaspero-variable-content> **<button class=\"closebutton\" (click)=\"resolve({resolved: false})\"> <i class=\"far fa-times-circle\"></i> </button>**</div> <div class=\"jaspero__confirmation_dialog-content\"> <jaspero-variable-content [isTemplate]=\"incomingData.messageIsTemplate\" [item]=\"incomingData.message\"></jaspero-variable-content> </div> <div class=\"jaspero__confirmation_dialog-actions\">  <button class=\"primary\" (click)=\"resolve({resolved: true})\" #focus> <jaspero-variable-content [isTemplate]=\"incomingData.confirmTextIsTemplate\" [item]=\"incomingData.confirmText\"></jaspero-variable-content> </button><button class=\"default\" (click)=\"resolve({resolved: false})\"> <jaspero-variable-content [isTemplate]=\"incomingData.declineTextIsTemplate\" [item]=\"incomingData.declineText\"></jaspero-variable-content> </button> </div> </div>",

i use a icon to close with the same functionality to the close button and works but when publish the project the changes losses.
