### ISSUE TITLE
Yes button not showing

### ISSUE THREAD

**Issue by Maden-maxi** [Jaspero/ng-confirmations#8]
![screenshot from 2017-10-27 18-05-46](https://user-images.githubusercontent.com/17612707/32110926-9f8914fa-bb41-11e7-83b8-d826a2b64f22.png)
Please make component styles customizable

**Comment by goncalvez** [comment]
Inspect your component. Maybe the css class of button is wrong or with wrong color.

**Comment by mkostiak** [comment]
I have the same issue... I have boostrap 4 installed and runing correctly... the other tools like NgNotifications, etc. run propertly... thanks for share your app's.

**Comment by aimtiaz11** [comment]
I am having the same issue. Its because the text color of the "primary" button is set to white. I dont get how the demo version is showing an orange button.

**Comment by flauc** [comment]
I'm sorry for the long wait, but this should be working now.
