### ISSUE TITLE
Yes button always white

### ISSUE THREAD

**Issue by pifaace** [Jaspero/ng-confirmations#9]
Hi !
Juste to report that I installed your module today and the confirmButton is color: white so I cant see it.

I saw that it was solved so i don't know what's wrong.

Thanks

**Comment by pifaace** [comment]
EDIT : Okey I solved my issue.
The problem was that on your website :https://jaspero.co/resources/projects/ng-confirmations
the package is **@jaspero/ng2-confirmations**, however on your repo it's **@jaspero/ng-confirmations**
;)

**Comment by flauc** [comment]
Yes sorry, we didn't get around to updating it on the site yet. That should be resolved pretty soon as well though.
